export enum ActionType {
  MOVE_CELL = 'cells/MOVE_CELL',
  DELETE_CELL = 'cells/DELETE_CELL',
  INSERT_CELL_AFTER = 'cells/INSERT_CELL_AFTER',
  UPDATE_CELL = 'cells/UPDATE_CELL',
  BUNDLE_START = 'bundles/BUNDLE_START',
  BUNDLE_COMPLETE = 'bundles/BUNDLE_COMPLETE'
}
